"use strict";

// DAT-004-T01 -- export domains, formats, limits and version metadata.
// The single contract every export module (service, controller, cron,
// frontend) is built against, so none of them can silently disagree about
// what a "domain", a "format", or an export's status even means.
//
// SCHEMA_VERSION is embedded in every export (a JSON export's own
// `meta.schemaVersion` field; a CSV export's first comment-prefixed line)
// so a user who re-imports or scripts against an old export can tell it
// apart from a future, differently-shaped one without guessing from
// column order.
const EXPORT_DOMAINS = Object.freeze({
  EXPENSES: "expenses",
  INCOME: "income",
  BUDGETS: "budgets",
  ALL: "all",
});
const EXPORT_DOMAIN_VALUES = Object.freeze(Object.values(EXPORT_DOMAINS));

const EXPORT_FORMATS = Object.freeze({ CSV: "csv", JSON: "json" });
const EXPORT_FORMAT_VALUES = Object.freeze(Object.values(EXPORT_FORMATS));

// "all" combines three differently-shaped tables (expenses/income/budgets)
// into one file. A single CSV can only hold one flat table, and building a
// multi-file archive would need a zip dependency this codebase does not
// have -- so "all" is deliberately JSON-only (one object with three
// top-level arrays); CSV requires one specific domain. This is a real,
// stated scope limit, not an oversight.
function isDomainFormatCombinationValid(domain, format) {
  if (domain === EXPORT_DOMAINS.ALL) return format === EXPORT_FORMATS.JSON;
  return EXPORT_FORMAT_VALUES.includes(format);
}

const EXPORT_STATUSES = Object.freeze({
  QUEUED: "queued",
  PROCESSING: "processing",
  READY: "ready",
  FAILED: "failed",
  EXPIRED: "expired",
});
const EXPORT_STATUS_VALUES = Object.freeze(Object.values(EXPORT_STATUSES));

const EXPORT_SCHEMA_VERSION = 1;

// Below this row count, DAT-004-T03's synchronous path generates and
// streams the file directly in the HTTP response -- no ExportRequest
// document, nothing written to disk, nothing to expire. At or above it,
// the request is queued (an ExportRequest with status "queued") and
// generated by cron/exportGeneration.js, because holding an HTTP response
// open for a potentially multi-minute generation is not viable and ties up
// a request worker the whole time.
const SYNC_ROW_LIMIT = 5000;

// Hard ceiling on ANY single export, sync or queued -- an unbounded query
// against a user's own full history is still an unbounded query. A request
// that would exceed this is rejected outright (400), not silently
// truncated: a truncated financial export that looks complete is worse
// than a clear refusal telling the user to narrow the date range.
const MAX_EXPORT_ROWS = 200000;

// How long a generated file (the queued path only) stays downloadable
// before cron/exportGeneration.js's sweep deletes it and marks the request
// "expired". Not user-configurable -- a fixed, generous window (a user
// who queues a large export and comes back the next day should still find
// it) that still bounds how much generated-file disk usage can accumulate.
const EXPORT_EXPIRY_HOURS = 24;

function isValidDomain(value) {
  return typeof value === "string" && EXPORT_DOMAIN_VALUES.includes(value);
}

function isValidFormat(value) {
  return typeof value === "string" && EXPORT_FORMAT_VALUES.includes(value);
}

// CSV formula-injection defense (DAT-004-T07's own requirement, applied
// everywhere a cell is written, not just in the test suite that checks
// it). A cell whose first character is one Excel/Sheets treats as a
// formula trigger (=, +, -, @) or a control character (tab, CR, LF) is
// prefixed with a leading apostrophe, which every spreadsheet application
// renders as literal text and never evaluates. Applied to every field,
// including ones that "shouldn't" contain user input (expenseCategory,
// incomeSource) -- those ARE user input in this app, just funneled through
// a text box rather than a dropdown, so treating them as safe by
// assumption is exactly the mistake this defense exists to close.
const FORMULA_TRIGGER_CHARS = new Set(["=", "+", "-", "@", "\t", "\r", "\n"]);

function sanitizeCsvCell(rawValue) {
  const value = rawValue === null || rawValue === undefined ? "" : String(rawValue);
  const needsFormulaGuard = value.length > 0 && FORMULA_TRIGGER_CHARS.has(value[0]);
  const guarded = needsFormulaGuard ? `'${value}` : value;
  // Standard CSV quoting: wrap in double quotes and escape embedded quotes
  // whenever the value contains a comma, quote, or newline (including one
  // introduced by the formula guard's leading apostrophe -- an apostrophe
  // itself needs no escaping, but the field may already contain a quote).
  if (/[",\n\r]/.test(guarded)) {
    return `"${guarded.replace(/"/g, '""')}"`;
  }
  return guarded;
}

function csvRow(values) {
  return values.map(sanitizeCsvCell).join(",") + "\r\n";
}

// A safe, predictable download filename -- never derived from user input
// (no merchant/category names), so it can never carry a path separator or
// a shell/formula-injection character itself.
function buildExportFileName(domain, format, generatedAt = new Date()) {
  const stamp = generatedAt
    .toISOString()
    .replace(/[-:]/g, "")
    .replace(/\.\d{3}Z$/, "Z")
    .replace("T", "-");
  return `balensia-export-${domain}-${stamp}.${format}`;
}

module.exports = {
  EXPORT_DOMAINS,
  EXPORT_DOMAIN_VALUES,
  EXPORT_FORMATS,
  EXPORT_FORMAT_VALUES,
  EXPORT_STATUSES,
  EXPORT_STATUS_VALUES,
  EXPORT_SCHEMA_VERSION,
  SYNC_ROW_LIMIT,
  MAX_EXPORT_ROWS,
  EXPORT_EXPIRY_HOURS,
  isValidDomain,
  isValidFormat,
  isDomainFormatCombinationValid,
  sanitizeCsvCell,
  csvRow,
  buildExportFileName,
};
